---
- name: Setup Guacamole
  hosts: Guacserver
  remote_user: dmzadmin
  become: true
  tasks:
     - name: Download and Install guac-install
       shell: git clone https://github.com/Dnshbbu/guac-install.git;cd guac-install;./guac-install.sh
       register: out
 
     - debug: var=out.stdout_lines

- name: Update packages in Kali machines
  hosts: KaliMachines
  strategy: free
  remote_user: kaliadmin
  become: true
  tasks:
    - name: Update
      shell: DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' update

    - name: Upgrade
      shell: DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' upgrade


  # tasks:
  #   - name: Update apt repo and cache on all Debian/Ubuntu boxes
  #     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  #   - name: Upgrade all packages on servers
  #     apt: upgrade=dist force_apt_get=yes


  
